modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

logoFile="logo.png"

[[mods]]
modId="${mod_id}"

version="${minecraft_version}-${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="terrablender"

mandatory=true

versionRange="[3.0.0.167,)"

ordering="AFTER"

side="BOTH"